- label: 'Test Build'
  command:
    - if [ ! -z "$MERGE_BRANCH" ]; then git merge $MERGE_BRANCH -m "merging $MERGE_BRANCH"; fi
    - curl https://rebar3.s3.amazonaws.com/rebar3 -o ./rebar3
    - chmod +x rebar3
    - ./rebar3 test
  agents:
    queue: 'rtb-new'
  plugins:
      - docker#v3.8.0:
          image: "771945457201.dkr.ecr.us-west-2.amazonaws.com/rtb/erts:27.3.4"
          always-pull: true
          propagate-environment: true
          propagate-aws-auth-tokens: true
          mount-ssh-agent: true
          workdir: /app